questions = [
    {'question': "What is the capital of Tunisia ? ",
     'A': "Sfax",
     'B': "Tunis",
     'C': "Sousse",
     'D': "Gabes",
     'correctKey': "B"
     },
    {'question': "What is the capital of France ? ",
     'A': "Paris",
     'B': "Marseille",
     'C': "Lyon",
     'D': "Toulouse",
     'correctKey': "A"
     },
    {'question': "What is the capital of Germany ? ",
     'A': "Cologne",
     'B': "Hamburg",
     'C': "Munich",
     'D': "Berlin",
     'correctKey': "D"
     },
    {'question': "What is the capital of Italy  ? ",
     'A': "Rome",
     'B': "Milan",
     'C': "Naples",
     'D': "Turin",
     'correctKey': "A"
     },
    {'question': "What is the capital of Spain  ? ",
     'A': "Valencia",
     'B': "Barcelona",
     'C': "Madrid",
     'D': "Seville",
     'correctKey': "C"
     },
    {'question': "What is the capital of Portugal  ? ",
     'A': "Porto",
     'B': "Lisbon",
     'C': "Coimbra",
     'D': "Braga",
     'correctKey': "B"
     },
    {'question': "What is the square of -11  ? ",
     'A': "144",
     'B': "121",
     'C': "169",
     'D': "100",
     'correctKey': "B"
     },
    {'question': "What is the square of 12  ? ",
     'A': "144",
     'B': "121",
     'C': "169",
     'D': "100",
     'correctKey': "A"
     },
    {'question': "What is the square of 9  ? ",
     'A': "89",
     'B': "121",
     'C': "72",
     'D': "81",
     'correctKey': "D"
     },
    {'question': "What is the square root of 64  ? ",
     'A': "8",
     'B': "6",
     'C': "7",
     'D': "9",
     'correctKey': "A"
     },
    {'question': "What is the square root of 100  ? ",
     'A': "8",
     'B': "6",
     'C': "7",
     'D': "10",
     'correctKey': "D"
     },
    {'question': "What is the square root of 49  ? ",
     'A': "8",
     'B': "6",
     'C': "7",
     'D': "9",
     'correctKey': "C"
     },
    {'question': "What is the square root of 49  ? ",
     'A': "8",
     'B': "6",
     'C': "7",
     'D': "9",
     'correctKey': "C"
     },
    {'question': "What does CRC stand for? ",
     'A': "Circle Redundancy Check",
     'B': "Cyclic Redundancy Check",
     'C': "Cyclic Redundancy Code",
     'D': "Circle Redundancy Code",
     'correctKey': "B"
     },
    {'question': "What does RAM stand for? ",
     'A': "Random Access Memory",
     'B': "Random Access Machine",
     'C': "Random Access Module",
     'D': "Random Access Multiprocessor",
        'correctKey': "A"
     },
    {'question': "In which layer is the information a Frame ",
     'A': "Application layer",
     'B': "Network layer",
     'C': "Transport layer",
     'D': "Data link layer",
        'correctKey': "D"
     },
]
